name: tlmtheme
description: Bootstrap 4 AngularDart Theme Default
version: 1.0.0
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  string_converters: ^1.0.0
  font_awesome: 4.7.0+1
  chartjs: ^0.5.0
  ng_bootstrap:
    git: https://github.com/dart-land/ng_bootstrap
  tlmThemeLogic:
    git: https://gitlab.com/trhhosting/tlmThemeLogic.git
dev_dependencies:
  test: ^1.3.0
  angular_test: ^2.0.0
  build_test: ^0.10.3+1
  build_runner: ^0.10.1+1
  build_web_compilers: ^0.4.3
  pageloader: ^3.0.0
  sass_builder: ^2.1.1
