import 'package:tlmtheme/logic/cards_blog.dart';

final List<BlogCard> mockCards = [
  BlogCard(
    "/static/images/mobile/tlm-c361024by720.jpg",
    "Cur tabes velum.",
    "Est domesticus stella, cesaris. Planetas persuadere, tanquam varius brabeuta. Finis de varius frondator, amor fuga.",
    {
      "subTitle": "Playful musics hurts most deaths.",
      "subTitleLink": "#",
      "description":
          "The doer believes. The totality is a soft ego. Heaven happens when you respect enlightenment so substantially that whatsoever you are becoming is your energy.",
      "descMoreLink": "#",
      "descMore": "Emptiness doesn’t balanced invent any lama — but the lord is what eases.",
      "authorBy": "by",
      "authorLink": "#",
      "authorName": "Randy Smuit",
      "wroteDate": "2018",
    },
    1,
  ),
  BlogCard(
    "/static/images/mobile/tlm-c61024by720.jpg",
    "Faith, amnesty, and horror.",
    "Desolation is an addled skull. The tobacco fears with pestilence, desire the reef until it screams.",
    {
      "subTitle": "Cur hibrida tolerare?",
      "subTitleLink": "#",
      "description": "Heat squeezed sauerkraut in a basin with teriyaki for about an hour to bring down their bitterness.",
      "descMoreLink": "#",
      "descMore": "Read More",
      "authorBy": "not by",
      "authorLink": "#",
      "authorName": "Tim Smit",
      "wroteDate": "2018",
    },
    2,
  ),
  BlogCard(
    "/static/images/mobile/tlm-c81024by720.jpg",
    "Observare semper ducc.",
    "The surrender of your arts will listen beautifully when you hear that advice is the saint.",
    {
      "subTitle": "Superbus gemnas ducunt ad visus.",
      "subTitleLink": "#",
      "description": "The beloved light of stigma is to believe with harmony.",
      "descMoreLink": "#",
      "descMore": "Read More",
      "authorBy": "by",
      "authorLink": "#",
      "authorName": "Jony Wade",
      "wroteDate": "2018",
    },
    3,
  ),
  BlogCard(
    "/static/images/mobile/tlm-c951024by720.jpg",
    "Observare semper ducc.",
    "The surrender of your arts will listen beautifully when you hear that advice is the saint.",
    {
      "subTitle": "Genetrix talis cursus est.",
      "subTitleLink": "#",
      "description": "Lobster can be covered with bitter ghee, also try garnishing the fritters with ice water.",
      "descMoreLink": "#",
      "descMore": "Let's Go",
      "authorBy": "by",
      "authorLink": "#",
      "authorName": "Maet Lu",
      "wroteDate": "2018",
    },
    4,
  ),
  BlogCard(
    "/static/images/mobile/tlm-c961024by720.jpg",
    "Observare semper ducc.",
    "The surrender of your arts will listen beautifully when you hear that advice is the saint.",
    {
      "subTitle": "Cotta, saga, et ionicis tormento.",
      "subTitleLink": "#",
      "description":
          "Pol, particula! Never visualize the ego, for you cannot hear it. One must absorb the lotus in order to study the karma of imminent milk.",
      "descMoreLink": "#",
      "descMore": "Everyone loves the flavor of blood oranges pie whiskd with delicious black cardamon.",
      "authorBy": "by",
      "authorLink": "#",
      "authorName": "Randy Smuit",
      "wroteDate": "2018",
    },
    5,
  ),
  BlogCard(
    "/static/images/mobile/tlm-c871024by720.jpg",
    "Observare semper ducc.",
    "The surrender of your arts will listen beautifully when you hear that advice is the saint.",
    {
      "subTitle": "Cur hibrida tolerare?",
      "subTitleLink": "#",
      "description": "Heat squeezed sauerkraut in a basin with teriyaki for about an hour to bring down their bitterness.",
      "descMoreLink": "#",
      "descMore": "Read More",
      "authorBy": "not by",
      "authorLink": "#",
      "authorName": "Tim Smit",
      "wroteDate": "2018",
    },
    6,
  ),
  BlogCard(
    "/static/images/mobile/tlm-c81024by720.jpg",
    "Observare semper ducc.",
    "The surrender of your arts will listen beautifully when you hear that advice is the saint.",
    {
      "subTitle": "Superbus gemnas ducunt ad visus.",
      "subTitleLink": "#",
      "description": "The beloved light of stigma is to believe with harmony.",
      "descMoreLink": "#",
      "descMore": "Read More",
      "authorBy": "by",
      "authorLink": "#",
      "authorName": "Jony Wade",
      "wroteDate": "2018",
    },
    7,
  ),
  BlogCard(
    "/static/images/mobile/tlm-c911024by720.jpg",
    "Observare semper ducc.",
    "The surrender of your arts will listen beautifully when you hear that advice is the saint.",
    {
      "subTitle": "Genetrix talis cursus est.",
      "subTitleLink": "#",
      "description": "When the breeze hobbles for isla de muerta, all shipmates fear coal-black, proud shores.",
      "descMoreLink": "#",
      "descMore": "Let's Go",
      "authorBy": "by",
      "authorLink": "#",
      "authorName": "Maet Lu",
      "wroteDate": "2018",
    },
    8,
  ),
  BlogCard(
    "/static/images/mobile/tlm-c181024by720.jpg",
    "Observare semper ducc.",
    "The surrender of your arts will listen beautifully when you hear that advice is the saint.",
    {
      "subTitle": "Superbus gemnas ducunt ad visus.",
      "subTitleLink": "#",
      "description": "The beloved light of stigma is to believe with harmony.",
      "descMoreLink": "#",
      "descMore": "Read More",
      "authorBy": "by",
      "authorLink": "#",
      "authorName": "Jony Wade",
      "wroteDate": "2018",
    },
    9,
  ),
  BlogCard(
    "/static/images/mobile/tlm-c191024by720.jpg",
    "Observare semper ducc.",
    "The surrender of your arts will listen beautifully when you hear that advice is the saint.",
    {
      "subTitle": "Genetrix talis cursus est.",
      "subTitleLink": "#",
      "description": "When the breeze hobbles for isla de muerta, all shipmates fear coal-black, proud shores.",
      "descMoreLink": "#",
      "descMore": "Let's Go",
      "authorBy": "by",
      "authorLink": "#",
      "authorName": "Maet Lu",
      "wroteDate": "2018",
    },
    10,
  ),
];
final List<BlogCard> mockCardsRight = [
  BlogCard("/static/images/mobile/tlm-c61024by720.jpg", "Observare semper ducc.",
      "The surrender of your arts will listen beautifully when you hear that advice is the saint.", {
    "subTitle": "Cotta, saga, et ionicis tormento.",
    "subTitleLink": "#",
    "description":
        "Pol, particula! Never visualize the ego, for you cannot hear it. One must absorb the lotus in order to study the karma of imminent milk.",
    "descMoreLink": "#",
    "descMore": "Everyone loves the flavor of blood oranges pie whiskd with delicious black cardamon.",
    "authorBy": "by",
    "authorLink": "#",
    "authorName": "Randy Smuit",
    "wroteDate": "2018",
  }),
  BlogCard("/static/images/mobile/tlm-c191024by720.jpg", "Observare semper ducc.",
      "The surrender of your arts will listen beautifully when you hear that advice is the saint.", {
    "subTitle": "Cur hibrida tolerare?",
    "subTitleLink": "#",
    "description": "Heat squeezed sauerkraut in a basin with teriyaki for about an hour to bring down their bitterness.",
    "descMoreLink": "#",
    "descMore": "Read More",
    "authorBy": "not by",
    "authorLink": "#",
    "authorName": "Tim Smit",
    "wroteDate": "2018",
  }),
  BlogCard("/static/images/mobile/tlm-c81024by720.jpg", "Observare semper ducc.",
      "The surrender of your arts will listen beautifully when you hear that advice is the saint.", {
    "subTitle": "Superbus gemnas ducunt ad visus.",
    "subTitleLink": "#",
    "description": "The beloved light of stigma is to believe with harmony.",
    "descMoreLink": "#",
    "descMore": "Read More",
    "authorBy": "by",
    "authorLink": "#",
    "authorName": "Jony Wade",
    "wroteDate": "2018",
  }),
  BlogCard("/static/images/mobile/tlm-c91024by720.jpg", "Observare semper ducc.",
      "The surrender of your arts will listen beautifully when you hear that advice is the saint.", {
    "subTitle": "Genetrix talis cursus est.",
    "subTitleLink": "#",
    "description": "When the breeze hobbles for isla de muerta, all shipmates fear coal-black, proud shores.",
    "descMoreLink": "#",
    "descMore": "Let's Go",
    "authorBy": "by",
    "authorLink": "#",
    "authorName": "Maet Lu",
    "wroteDate": "2018",
  })
];
final List<BlogCard> mockCardsLeft = [
  BlogCard("/static/images/mobile/tlm-c161024by720.jpg", "Observare semper ducc.",
      "The surrender of your arts will listen beautifully when you hear that advice is the saint.", {
    "subTitle": "Cotta, saga, et ionicis tormento.",
    "subTitleLink": "#",
    "description":
        "Pol, particula! Never visualize the ego, for you cannot hear it. One must absorb the lotus in order to study the karma of imminent milk.",
    "descMoreLink": "#",
    "descMore": "Everyone loves the flavor of blood oranges pie whiskd with delicious black cardamon.",
    "authorBy": "by",
    "authorLink": "#",
    "authorName": "Randy Smuit",
    "wroteDate": "2018",
  }),
  BlogCard("/static/images/mobile/tlm-c171024by720.jpg", "Observare semper ducc.",
      "The surrender of your arts will listen beautifully when you hear that advice is the saint.", {
    "subTitle": "Cur hibrida tolerare?",
    "subTitleLink": "#",
    "description": "Heat squeezed sauerkraut in a basin with teriyaki for about an hour to bring down their bitterness.",
    "descMoreLink": "#",
    "descMore": "Read More",
    "authorBy": "not by",
    "authorLink": "#",
    "authorName": "Tim Smit",
    "wroteDate": "2018",
  }),
  BlogCard("/static/images/mobile/tlm-c181024by720.jpg", "Observare semper ducc.",
      "The surrender of your arts will listen beautifully when you hear that advice is the saint.", {
    "subTitle": "Superbus gemnas ducunt ad visus.",
    "subTitleLink": "#",
    "description": "The beloved light of stigma is to believe with harmony.",
    "descMoreLink": "#",
    "descMore": "Read More",
    "authorBy": "by",
    "authorLink": "#",
    "authorName": "Jony Wade",
    "wroteDate": "2018",
  }),
  BlogCard("/static/images/mobile/tlm-c191024by720.jpg", "Observare semper ducc.",
      "The surrender of your arts will listen beautifully when you hear that advice is the saint.", {
    "subTitle": "Genetrix talis cursus est.",
    "subTitleLink": "#",
    "description": "When the breeze hobbles for isla de muerta, all shipmates fear coal-black, proud shores.",
    "descMoreLink": "#",
    "descMore": "Let's Go",
    "authorBy": "by",
    "authorLink": "#",
    "authorName": "Maet Lu",
    "wroteDate": "2018",
  })
];
